name: aurum_fo
description: Aurum FO Protocol App

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: any
  animate_do: any
  geolocator: any
  camera: any
  local_auth: any
  url_launcher: any

flutter:
  uses-material-design: true